### ISSUE TITLE
additional .ino sketch should not be here : must be removed

### ISSUE THREAD

**Issue by derrgis** [derrgis/corridor#10]
JQ6500MQTTPLAYER.ino and JQ6500_ESP01-HelloWorld.ino are test sketch and should not be in that repos.

How to remove and erase them?

**Comment by Liliputech** [comment]
will do.

**Comment by derrgis** [comment]
Please don't erase. 
New repos needed for JQ6500MQTTPLAYER.ino

**Comment by Liliputech** [comment]
Ok I'll wait until you create a new one then.
