### ISSUE TITLE
TIME MANAGEMENT

### ISSUE THREAD

**Issue by derrgis** [derrgis/corridor#12]
Proposition du mode de gestion des "ledPattern" 

/ Lors d'une nouvelle publication un nouvel affichage est lancé /
• option A/ l'ancien affichage disparait directement et le nouvel affichage démarre
• option B/ l'ancien affichage reste statique et visible et le nouvel affichage démarre
• option C/ l'ancien affichage suit son cours tandis que le nouvel affichage tuile l'ancien
• option D/  la nouvelle publication est stockée dans un buffer en attente de son tour et l'ancien affichage se termine en premier lieu

/ Durée des ledPattern /
• option A/ la durée ne dépend que de la durée discète de la fonction appelé, 
problème > aucun controle donc et très difficile de créer une partition avec des sons ayant eux-même leur propre durée
• option B/ la durée est liée à un nombre de boucle donné (holdPattern)
problème > similaire au point précédent
• option C/ la durée est donnée précisément en mn/sec/ms via une publication spécifique

Tout ceci est probablement possible ?
https://github.com/marmilicious/FastLED_examples/blob/master/every_n_timers.ino

Deadline finale, toutes validations incluses : 28 octobre.

**Comment by derrgis** [comment]
Changement : projet ouvert

**Comment by Liliputech** [comment]
faut donc choisir une des options pour chacun des problèmes évoqués, par contre je dirais que ce sont deux problèmes distincts, qu'en pense tu?

**Comment by Liliputech** [comment]
concernant le premier problème, pour le moment c'est le fonctionnement B qui s'applique.
Pour faciliter le suivi de chacun des problèmes c'est mieux de les créer chacun dans des tickets (issues) séparés.

**Comment by derrgis** [comment]
Comme il va y avoir une partition (script bash) pour conduire les ESP, le déclenchement d'un nouveau pattern (depuis le bash donc) doit être pris en compte à la fin de la boucle en cours.
Avec cette option suivante (bonne option artistiquement parlant)
• option C/ l'ancien affichage suit son cours tandis que le nouvel affichage tuile l'ancien
