### ISSUE TITLE
Durée d'un pattern

### ISSUE THREAD

**Issue by Liliputech** [derrgis/corridor#13]
Durée des ledPattern /
• option A/ la durée ne dépend que de la durée discète de la fonction appelé,
problème > aucun controle donc et très difficile de créer une partition avec des sons ayant eux-même leur propre durée
• option B/ la durée est liée à un nombre de boucle donné (holdPattern)
problème > similaire au point précédent
• option C/ la durée est donnée précisément en mn/sec/ms via une publication spécifique

En l'état actuel le pattern courant est joué jusqu'à ce qu'un nouveau pattern soit reçu par MQTT.

**Comment by Liliputech** [comment]
à valider : https://github.com/derrgis/corridor/pull/14

**Comment by Liliputech** [comment]
du neuf à ce sujet?

**Comment by derrgis** [comment]
Actuellement aucune notion de durée ni en temps ni en nombre de boucle ne semble fonctionner. Ce qui peut-être bien : avoir un  controle sur la durée d'un pattern déclenché mais si le script bash fait une nouvelle publication celui-ci à raison sur le cours. Le nouveau pattern est triggé dès la fin de la boucle en cours (sans attendre le nombre la fin de la durée prévue).
